app_name = "payment_integration_utils"
app_title = "Payment Integration Utils"
app_publisher = "Resilient Tech"
app_description = "Base for integrate online payment integrations"
app_email = "info@resilient.tech"
app_license = "mit"
